[package]
name = "helm-preset"
version = "0.1.0"
authors = ["Daniel <codinaut@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "^1.0.114", features = ["derive"] }
serde_yaml = "^0.8.13"
snafu = "^0.6.8"

[dev-dependencies]
fake = "^2.2.3"
maplit = "^1.0.2"
